mysql:
  username: appli
  host: mariadb
  port: 3306
  database: api-users
api:
  port: 8080
  prometheus_exporter_port: 8081
jwt:
  refresh_token:
    jwt_sign_method: RS512
    private_cert: /certs/refresh_jwt.key
    public_cert: /certs/refresh_jwt.key.pub
  access_token:
    jwt_sign_method: RS512
    private_cert: /certs/access_jwt.key
    public_cert: /certs/access_jwt.key.pub
rbac: 
  model: /rbac/rbac_model.conf
  policy: /rbac/rbac_policy.csv
security:
  bcrypt_hash_cost: 13
  enable_su: true
  su_login: root
  enable_local_register: true
  attributed_role_on_register: user