mysql:
  username: root
  password: root
  host: localhost
  port: 3306
  database: dev-env
api:
  port: 8080
  prometheus_exporter_port: 8081
jwt:
  refresh_token:
    jwt_sign_method: HS512
    secret_key: weak
  access_token:
    jwt_sign_method: HS512
    secret_key: weak
rbac: 
  model: ./ressources/rbac/rbac_model.conf
  policy: ./ressources/rbac/rbac_policy.csv
security:
  bcrypt_hash_cost: 13
  enable_su: true
  su_login: root
  su_password: root
  enable_local_register: true
  attributed_role_on_register: user